name: Build

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - feature/*
      - bugfix/*

jobs:
  build-and-deploy-documentation:
    strategy:
      matrix:
        java: ["17"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - JDK ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Gradle caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.java }}-${{ matrix.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.os }}-gradle-caches-
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ matrix.java }}-${{ matrix.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.os }}-gradle-wrapper-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Build, run tests and generate code coverage reports
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

      - name: Publish Kover coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Aggregated Kover report
          files: build/reports/kover/xml/report.xml

      - name: Build Dokka
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: Deploy documentation to GitHub Pages
        if: ${{ matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          clean: true
          single-commit: true